### PR TITLE
Test Question 1 Commit

### PR DESCRIPTION
**Pull request by MishaHerscu**
I just wanted to make sure I can do this correctly. I'll ping Jon soon, but my questions are just whether this is the right way to submit my hw and also, whether this is a good format for the actual answer to the first question. Thanks.

### CODE REVIEW

**Comment by jonblum** [comment]
Looks good, though your screenshot seems to be a powerpoint file?  And you've got everything in a 'question1' directory -- not sure if you're planning to make a separate directory for each question, but you may want to wrap all of them in a 'HW1' directory, or things'll get confusing come HW2.

**Comment by MishaHerscu** [comment]
okay, thanks - what format should i make the screenshot? i just saved it into a ppt, but i can do something else too

**Comment by jonblum** [comment]
PNG/JPG/any other image format should be fine.

**Comment by MishaHerscu** [comment]
okay, thanks

**Pull request closed without merging**
