### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by jcorrado725**

### CODE REVIEW

**Comment by jonblum** [comment]
Hi -- looks like you've added a file to your fork, but it's not its own FirstnameLastname directory.  Can you create that directory, so we can keep everyone's HW separate, going forward?

**Comment by jcorrado725** [comment]
Hi Jon,

I'm sorry, just so I understand, are you asking me to rename the folder on
my comp to DS_BOS_07_Students/JeffreyCorrado?
ᐧ

**Comment by jonblum** [comment]
Not renaming, but actually creating a JeffreyCorrado directory inside DS_BOS_07_Students, and then putting a file inside that nested directory.

**Comment by jcorrado725** [comment]
Ahh ok, thanks Jon, I appreciate the clarification.
ᐧ

**Comment by jcorrado725** [comment]
Hi Jon,

Sorry to keep bugging you.  Just created the folder and tried to commit it
to the repository but am still not seeing my folder.  I've read through the
tutorials and am not quite sure what I am doing wrong.  Might you be able
to point me in the right direction?  Sorry, I know this is basic stuff.
ᐧ

**Comment by jonblum** [comment]
There's a lot of tricky conceptual stuff at play here, so no worries! 
It looks like you successfully made the changes to your fork and pushed them upstream to GitHub: [your fork repo](https://github.com/jcorrado725/DS_BOS_07_Students) shows your directory.

The final step is to issue a pull request (PR) to bring the changes from your fork into the original student repo (this one, the pburkard88 one).  But you've already done that -- we're commenting on your original PR.  I noticed you closed the PR, but you didn't have to: any additional commits (in response to comments, for example) are automatically brought into the PR.  So when I'm done typing this comment, I'm going to reopen your PR.  Your changes (the new directory) should be incorporated, and then I'll accept the PR and merge your changes into Paul's repo.

**Comment by jcorrado725** [comment]
Thank you Jon... I appreciate it.  Makes more sense now.  Thank you!
ᐧ

**Pull request merged**
